spring:
  application:
    name: java-tech-test

logging:
  level:
    root: info
    com.csoftz.gap.java.tech.test : info

piggy:
  bank:
    valid:
      coin:
        values: abc,   50,100,200,500,1000
